### ISSUE TITLE
"Run Script" Action.

### ISSUE THREAD

**Issue by imraro** [lordgreg/Sfen#24]
It might be killer-feature.

**Comment by generalmanager** [comment]
I just tried this feature on Android 5.1.1, but it doesn't seem to work. Executing test scripts like the examples above works with Terminal Emulator (even without root) inside the /storage/emulated/0/Download directory, but doesn't work with Sfen. Neither when using a local path (aka touch asd.txt) nor when using the absolute path (touch /storage/emulated/0/Download/asd.txt).

I tried using Sfen in root mode and without, but it doesn't work in any of those. Could you maybe check if this still works for you?
